import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Manrope, Stack_Sans_Notch } from "next/font/google";
import "./globals.css";

const stack_sans_notch = Stack_Sans_Notch({
  variable: "--font-stack-sans-notch",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        stack_sans_notch.variable,
        manrope.variable,
        "font-manrope",
      )}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
